name: Build Atlantis custom image
on: push

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build an push the image
              run: |
                echo "${{ secrets.GHA_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
                export IMAGE_NAME=ghcr.io/${{ github.repository }}
                export TG_VERSION=0.73.6
                export ATLANTIS_VERSION=0.33.0
                export IMAGE_TAG=$ATLANTIS_VERSION-${{ github.run_number }}
                ./customize.sh
            - name: Push the image
              if: github.ref_name == github.event.repository.default_branch
              run: |
                docker push $IMAGE_NAME:$IMAGE_TAG
