name: Build Atlantis custom image
on: push

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}
          TG_VERSION: 0.73.6
          ATLANTIS_VERSION: 0.33.0
          IMAGE_TAG: ${{ env.ATLANTIS_VERSION }}-${{ github.run_number }}
        steps:
            - uses: actions/checkout@v3
            - name: Build an push the image
              run: |
                echo "${{ secrets.GHA_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
                ./customize.sh
            - name: Push the image
              if: github.ref_name == github.event.repository.default_branch
              run: |
                docker push $IMAGE_NAME:$IMAGE_TAG
